title: Hello, world! I'm Asia Hewett 
description: > # this means to ignore newlines until "baseurl:"
  English major exploring the utility and convenience of becoming tech savvy. Having completed my data analysis bootcamp I am now using this platform as an opportunity to share my experience with others who may be exploring their options in the world of code.
permalink: ':title/'
baseurl: "/continental_blog_spot" # the subpath of your site, e.g. /blog
url: "https://asia-hewett.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Asia Hewett # add your name
author-img: img_asset.jpeg # add your photo
about-author: Business Intelligence and Data Analyst. Always looking for more to explore! # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: Asia-Hewett # add your Github handle
social-linkedin: asia-hewett# add your Linkedin handle
social-email: asia.hewett0046@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: Asia Hewett # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
